[build-system]
requires = ["setuptools>=64"]
build-backend = "setuptools.build_meta"

[project]
name = "parch-kernel-manager"
version = "1.1.0"
description = "A modern kernel management application for Parch GNU/Linux"

readme = "README.md"
license = {text = "AGPL-3.0-or-later"}
requires-python = ">=3.9"
dependencies = []

[project.scripts]
parch-kernel-manager = "pkm.app:main"

[project.urls]
Homepage = "https://parchlinux.com"
Issues = "https://github.com/parchlinux/PKM/issues"

[tool.setuptools.packages.find]
include = ["pkm*"]

[tool.setuptools.data-files]
"share/applications" = ["data/com.parchlinux.kernelmanager.desktop"]
"share/icons/hicolor/scalable/apps" = ["data/com.parchlinux.kernelmanager.svg"]
